Feature/todo
hamidazim321/to-do-app-react pull request #1
Opened 2023-08-14 12:06 UTC by hamidazim321

In this PR:
- I have made a todo list using react that allows users to add, edit, mark as complete, and delete list items
- The list data is preserved in the local storage

2023-08-14 14:06 UTC, Wineshuga requested changes
### Changes Required @hamidazim321.

**Great job so far!** 🙌 

- [ ] No linter errors ✔️ 
- [ ] Descriptive PR ✔️
- [ ] Good commit messages ✔️
- [ ] Good use of React concepts learned ✔️
- [ ] Followed JavaScript best practices ✔️
- [ ] Project works as expected

Please, kindly take note of the following suggestion that can help improve your work.
Happy coding 👍

2023-08-14 14:07 UTC, Wineshuga commented on README.md
> +# Getting Started with Create React App
I would suggest that you kindly think about making the README file descriptive and customized to your project. I believe this would aid in making your repo more professional.

2023-08-15 07:38 UTC, hamidazim321 commented on README.md
> +# Getting Started with Create React App
Thank you @Wineshuga, I have made the required changes. Can you take another look :blush:

2023-08-15 08:35 UTC, Wineshuga approved these changes
### Merge Approved @hamidazim321 

**Great work working on the suggested changes 💯 ** 
There's else to do but merge. 🥇

2023-08-15 09:58 UTC, merged